# Generated by Django 5.0.4 on 2024-04-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movierecommendation", "0002_doubanmovieindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeiboCommentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_keyword", models.CharField(max_length=256)),
                ("comment_doclist", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeiboComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.BigIntegerField(null=True)),
                ("create_date_time", models.DateTimeField(null=True)),
                ("content", models.TextField(null=True)),
                ("sub_comment_count", models.IntegerField(null=True)),
                ("comment_like_count", models.IntegerField(null=True)),
                ("ip_location", models.CharField(max_length=255, null=True)),
                ("user_id", models.BigIntegerField(null=True)),
                ("nickname", models.CharField(max_length=255, null=True)),
                ("gender", models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
