# Generated by Django 5.0.4 on 2024-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movierecommendation", "0003_weibocommentindex_weibocomments"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeiboNoteIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_keyword", models.CharField(max_length=256)),
                ("note_doclist", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeiboNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_id", models.BigIntegerField(null=True)),
                ("content", models.TextField(null=True)),
                ("create_date_time", models.DateTimeField(null=True)),
                ("liked_count", models.IntegerField(null=True)),
                ("comments_count", models.IntegerField(null=True)),
                ("shared_count", models.IntegerField(null=True)),
                ("ip_location", models.CharField(max_length=255, null=True)),
                ("user_id", models.BigIntegerField(null=True)),
                ("nickname", models.CharField(max_length=255, null=True)),
                ("gender", models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
