# Generated by Django 5.0.4 on 2024-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movierecommendation", "0004_weibonoteindex_weibonotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
    ]
